Traceback (most recent call last):
  File "D:\users\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 64, in single_nb_execution
    **kwargs,
  File "D:\users\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\users\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\users\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\users\anaconda3\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "D:\users\anaconda3\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "D:\users\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\users\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Todo

x = 24
r.insert(binarySearch(r, x), x )
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32m<ipython-input-9-33969a5dd8a5>[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [0mx[0m [1;33m=[0m [1;36m24[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 4[1;33m [0mr[0m[1;33m.[0m[0minsert[0m[1;33m([0m[0mbinarySearch[0m[1;33m([0m[0mr[0m[1;33m,[0m [0mx[0m[1;33m)[0m[1;33m,[0m [0mx[0m [1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m
[1;31mTypeError[0m: 'NoneType' object cannot be interpreted as an integer
TypeError: 'NoneType' object cannot be interpreted as an integer

