Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 608, in async_setup_kernel
    yield
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
count = 0
while count < 5 :
    pw=input('password')
    if pw=='pythonisfun':
       print('로그인 되었습니다.')
       break
    count = count + 1    
else:
    print ('로그인에 실패했습니다.')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
Cell [1;32mIn[25], line 3[0m
[0;32m      1[0m count [38;5;241m=[39m [38;5;241m0[39m
[0;32m      2[0m [38;5;28;01mwhile[39;00m count [38;5;241m<[39m [38;5;241m5[39m :
[1;32m----> 3[0m     pw[38;5;241m=[39m[38;5;28;43minput[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mpassword[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      4[0m     [38;5;28;01mif[39;00m pw[38;5;241m==[39m[38;5;124m'[39m[38;5;124mpythonisfun[39m[38;5;124m'[39m:
[0;32m      5[0m        [38;5;28mprint[39m([38;5;124m'[39m[38;5;124m로그인 되었습니다.[39m[38;5;124m'[39m)

File [1;32m~\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\kernelbase.py:1190[0m, in [0;36mKernel.raw_input[1;34m(self, prompt)[0m
[0;32m   1188[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mself[39m[38;5;241m.[39m_allow_stdin:
[0;32m   1189[0m     msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mraw_input was called, but this frontend does not support input requests.[39m[38;5;124m"[39m
[1;32m-> 1190[0m     [38;5;28;01mraise[39;00m StdinNotImplementedError(msg)
[0;32m   1191[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_input_request(
[0;32m   1192[0m     [38;5;28mstr[39m(prompt),
[0;32m   1193[0m     [38;5;28mself[39m[38;5;241m.[39m_parent_ident[[38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m],
[0;32m   1194[0m     [38;5;28mself[39m[38;5;241m.[39mget_parent([38;5;124m"[39m[38;5;124mshell[39m[38;5;124m"[39m),
[0;32m   1195[0m     password[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[0;32m   1196[0m )

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

